#############################################################################
# Makefile for building: CampaignTool.app/Contents/MacOS/CampaignTool
# Generated by qmake (2.01a) (Qt 4.8.0) on: Thu Oct 11 22:22:01 2012
# Project:  CampaignTool.pro
# Template: app
# Command: /Users/gardan/QtSDK/Desktop/Qt/480/gcc/bin/qmake -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile CampaignTool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtSql.framework/Versions/4/Headers -I/usr/include/QtSql -I/usr/include -I. -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtSql -framework QtCore -framework QtGui 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/gardan/QtSDK/Desktop/Qt/480/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		campaigntool.cpp \
		store.cpp \
		mapstore.cpp \
		force.cpp \
		forcelance.cpp \
		forcecompany.cpp \
		forcebattalion.cpp \
		forceregiment.cpp \
		forcerct.cpp \
		mapnode.cpp \
		mapmodel.cpp \
		mw.cpp \
		mwattribute.cpp \
		mwskill.cpp \
		mwtrait.cpp \
		mech.cpp \
		mechlocation.cpp \
		vehicle.cpp \
		vehiclelocation.cpp \
		equipment.cpp \
		weapon.cpp \
		weaponammo.cpp \
		dice.cpp \
		../CharacterGenerator/attributemodel.cpp moc_campaigntool.cpp \
		moc_mapmodel.cpp \
		moc_attributemodel.cpp
OBJECTS       = main.o \
		campaigntool.o \
		store.o \
		mapstore.o \
		force.o \
		forcelance.o \
		forcecompany.o \
		forcebattalion.o \
		forceregiment.o \
		forcerct.o \
		mapnode.o \
		mapmodel.o \
		mw.o \
		mwattribute.o \
		mwskill.o \
		mwtrait.o \
		mech.o \
		mechlocation.o \
		vehicle.o \
		vehiclelocation.o \
		equipment.o \
		weapon.o \
		weaponammo.o \
		dice.o \
		attributemodel.o \
		moc_campaigntool.o \
		moc_mapmodel.o \
		moc_attributemodel.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		CampaignTool.pro
QMAKE_TARGET  = CampaignTool
DESTDIR       = 
TARGET        = CampaignTool.app/Contents/MacOS/CampaignTool

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile CampaignTool.app/Contents/PkgInfo CampaignTool.app/Contents/Resources/empty.lproj CampaignTool.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_campaigntool.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) CampaignTool.app/Contents/MacOS/ || $(MKDIR) CampaignTool.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CampaignTool.pro  /usr/local/Qt4.8/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-base.conf \
		/usr/local/Qt4.8/mkspecs/common/g++-macx.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/qt.prf \
		/usr/local/Qt4.8/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.8/mkspecs/features/moc.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtSql.framework/QtSql.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile CampaignTool.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/g++-base.conf:
/usr/local/Qt4.8/mkspecs/common/g++-macx.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/qt.prf:
/usr/local/Qt4.8/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.8/mkspecs/features/moc.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtSql.framework/QtSql.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/macx-g++ CONFIG+=x86_64 -o Makefile CampaignTool.pro

CampaignTool.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) CampaignTool.app/Contents || $(MKDIR) CampaignTool.app/Contents 
	@$(DEL_FILE) CampaignTool.app/Contents/PkgInfo
	@echo "APPL????" >CampaignTool.app/Contents/PkgInfo
CampaignTool.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) CampaignTool.app/Contents/Resources || $(MKDIR) CampaignTool.app/Contents/Resources 
	@touch CampaignTool.app/Contents/Resources/empty.lproj
	
CampaignTool.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) CampaignTool.app/Contents || $(MKDIR) CampaignTool.app/Contents 
	@$(DEL_FILE) CampaignTool.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,CampaignTool,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.8/mkspecs/macx-g++/Info.plist.app >CampaignTool.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/CampaignTool1.0.0 || $(MKDIR) .tmp/CampaignTool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CampaignTool1.0.0/ && $(COPY_FILE) --parents campaigntool.h store.h mapstore.h force.h forcelance.h forcecompany.h forcebattalion.h forceregiment.h forcerct.h mapnode.h mapmodel.h mw.h mwattribute.h mwskill.h mwtrait.h mech.h mechlocation.h vehicle.h vehiclelocation.h equipment.h weapon.h weaponammo.h dice.h ../CharacterGenerator/attributemodel.h .tmp/CampaignTool1.0.0/ && $(COPY_FILE) --parents main.cpp campaigntool.cpp store.cpp mapstore.cpp force.cpp forcelance.cpp forcecompany.cpp forcebattalion.cpp forceregiment.cpp forcerct.cpp mapnode.cpp mapmodel.cpp mw.cpp mwattribute.cpp mwskill.cpp mwtrait.cpp mech.cpp mechlocation.cpp vehicle.cpp vehiclelocation.cpp equipment.cpp weapon.cpp weaponammo.cpp dice.cpp ../CharacterGenerator/attributemodel.cpp .tmp/CampaignTool1.0.0/ && $(COPY_FILE) --parents campaigntool.ui .tmp/CampaignTool1.0.0/ && (cd `dirname .tmp/CampaignTool1.0.0` && $(TAR) CampaignTool1.0.0.tar CampaignTool1.0.0 && $(COMPRESS) CampaignTool1.0.0.tar) && $(MOVE) `dirname .tmp/CampaignTool1.0.0`/CampaignTool1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CampaignTool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r CampaignTool.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_campaigntool.cpp moc_mapmodel.cpp moc_attributemodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_campaigntool.cpp moc_mapmodel.cpp moc_attributemodel.cpp
moc_campaigntool.cpp: mapmodel.h \
		mapnode.h \
		ui_campaigntool.h \
		campaigntool.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ campaigntool.h -o moc_campaigntool.cpp

moc_mapmodel.cpp: mapnode.h \
		mapmodel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mapmodel.h -o moc_mapmodel.cpp

moc_attributemodel.cpp: ../CharacterGenerator/attribute.h \
		../CharacterGenerator/attributemodel.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ../CharacterGenerator/attributemodel.h -o moc_attributemodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_campaigntool.h
compiler_uic_clean:
	-$(DEL_FILE) ui_campaigntool.h
ui_campaigntool.h: campaigntool.ui
	/Developer/Tools/Qt/uic campaigntool.ui -o ui_campaigntool.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp campaigntool.h \
		mapmodel.h \
		mapnode.h \
		ui_campaigntool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

campaigntool.o: campaigntool.cpp campaigntool.h \
		mapmodel.h \
		mapnode.h \
		ui_campaigntool.h \
		dice.h \
		mech.h \
		mechlocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o campaigntool.o campaigntool.cpp

store.o: store.cpp store.h \
		mech.h \
		mechlocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o store.o store.cpp

mapstore.o: mapstore.cpp mapstore.h \
		dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapstore.o mapstore.cpp

force.o: force.cpp force.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o force.o force.cpp

forcelance.o: forcelance.cpp forcelance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forcelance.o forcelance.cpp

forcecompany.o: forcecompany.cpp forcecompany.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forcecompany.o forcecompany.cpp

forcebattalion.o: forcebattalion.cpp forcebattalion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forcebattalion.o forcebattalion.cpp

forceregiment.o: forceregiment.cpp forceregiment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forceregiment.o forceregiment.cpp

forcerct.o: forcerct.cpp forcerct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o forcerct.o forcerct.cpp

mapnode.o: mapnode.cpp mapnode.h \
		mapstore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapnode.o mapnode.cpp

mapmodel.o: mapmodel.cpp mapmodel.h \
		mapnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mapmodel.o mapmodel.cpp

mw.o: mw.cpp mw.h \
		mwskill.h \
		mwtrait.h \
		mwattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mw.o mw.cpp

mwattribute.o: mwattribute.cpp mwattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mwattribute.o mwattribute.cpp

mwskill.o: mwskill.cpp mwskill.h \
		mw.h \
		mwtrait.h \
		mwattribute.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mwskill.o mwskill.cpp

mwtrait.o: mwtrait.cpp mwtrait.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mwtrait.o mwtrait.cpp

mech.o: mech.cpp mech.h \
		mechlocation.h \
		store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mech.o mech.cpp

mechlocation.o: mechlocation.cpp mechlocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mechlocation.o mechlocation.cpp

vehicle.o: vehicle.cpp vehicle.h \
		vehiclelocation.h \
		equipment.h \
		weapon.h \
		store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vehicle.o vehicle.cpp

vehiclelocation.o: vehiclelocation.cpp vehiclelocation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vehiclelocation.o vehiclelocation.cpp

equipment.o: equipment.cpp equipment.h \
		store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equipment.o equipment.cpp

weapon.o: weapon.cpp weapon.h \
		store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o weapon.o weapon.cpp

weaponammo.o: weaponammo.cpp store.h \
		weaponammo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o weaponammo.o weaponammo.cpp

dice.o: dice.cpp dice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dice.o dice.cpp

attributemodel.o: ../CharacterGenerator/attributemodel.cpp ../CharacterGenerator/attributemodel.h \
		../CharacterGenerator/attribute.h \
		../CharacterGenerator/attributestore.h \
		../CharacterGenerator/store.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o attributemodel.o ../CharacterGenerator/attributemodel.cpp

moc_campaigntool.o: moc_campaigntool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_campaigntool.o moc_campaigntool.cpp

moc_mapmodel.o: moc_mapmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mapmodel.o moc_mapmodel.cpp

moc_attributemodel.o: moc_attributemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_attributemodel.o moc_attributemodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

